site_name: 'Surfers-FastAPI-Accelerator'
repo_url: https://github.com/surfers-lookout/surfers-fastapi-accelerator
repo_name: Github
edit_uri: blob/main/docs/
docs_dir: docs
nav:
  - Home: index.md
  - Tasks: tasks.md
  - Bugs: bugs.md
plugins:
  - techdocs-core
